package com.camnet.app

import android.Manifest
import android.annotation.SuppressLint
import android.content.pm.PackageManager
import android.net.http.SslError
import android.os.Bundle
import android.webkit.*
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat

class MainActivity : AppCompatActivity() {

    lateinit var webView: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        requestPermissions()

        webView = WebView(this).also { setContentView(it) }

        webView.settings.apply {
            javaScriptEnabled = true
            domStorageEnabled = true
            mediaPlaybackRequiresUserGesture = false
            allowFileAccessFromFileURLs = true
            allowUniversalAccessFromFileURLs = true
            mixedContentMode = WebSettings.MIXED_CONTENT_ALWAYS_ALLOW
        }

        webView.addJavascriptInterface(
            AndroidBridge(this) { url -> webView.loadUrl(url) },
            "AndroidBridge"
        )

        webView.webViewClient = object : WebViewClient() {
            @SuppressLint("WebViewClientOnReceivedSslError")
            override fun onReceivedSslError(view: WebView, handler: SslErrorHandler, error: SslError) {
                // Accept the self-signed cert generated by the Termux server
                handler.proceed()
            }

            override fun onReceivedError(view: WebView, request: WebResourceRequest, error: WebResourceError) {
                if (request.isForMainFrame) runOnUiThread { showSetup() }
            }
        }

        webView.webChromeClient = object : WebChromeClient() {
            override fun onPermissionRequest(request: PermissionRequest) {
                request.grant(request.resources)
            }
        }

        val saved = getSharedPreferences("camnet", MODE_PRIVATE).getString("server_url", null)
        if (saved != null) webView.loadUrl("$saved/camera.html") else showSetup()
    }

    fun showSetup() {
        webView.loadDataWithBaseURL(null, setupHtml(), "text/html", "UTF-8", null)
    }

    private fun setupHtml(): String = """
        <!DOCTYPE html><html><head>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
        <style>
          *{box-sizing:border-box;margin:0;padding:0}
          body{background:#090910;color:#f1f5f9;font-family:-apple-system,sans-serif;
               display:flex;flex-direction:column;align-items:center;justify-content:center;
               min-height:100vh;padding:32px 24px;gap:16px}
          h1{font-size:22px;font-weight:700}
          p{color:#94a3b8;font-size:14px;text-align:center;line-height:1.5;max-width:300px}
          input{width:100%;padding:14px 16px;font-size:16px;background:#1e293b;color:#f1f5f9;
                border:1.5px solid #334155;border-radius:14px;outline:none}
          input:focus{border-color:#3b82f6}
          button{width:100%;padding:15px;background:#3b82f6;color:#fff;border:none;
                 border-radius:14px;font-size:16px;font-weight:600;cursor:pointer;
                 -webkit-tap-highlight-color:transparent}
          .hint{color:#475569;font-size:12px;text-align:center}
        </style></head><body>
        <h1>CamNet Camera</h1>
        <p>Enter the URL shown when you run <code>npm start</code> in Termux</p>
        <input id="url" type="url" placeholder="https://192.168.x.x:3000"
               autocomplete="off" autocorrect="off" spellcheck="false">
        <button onclick="save()">Connect &rarr;</button>
        <p class="hint">Tap Advanced &rarr; Proceed if your browser warns about the certificate</p>
        <script>
          document.getElementById('url').focus();
          function save(){
            var v=document.getElementById('url').value.trim().replace(/\/+$/,'');
            if(!v)return;
            AndroidBridge.setServerUrl(v);
          }
          document.getElementById('url').addEventListener('keydown',function(e){
            if(e.key==='Enter')save();
          });
        </script></body></html>
    """.trimIndent()

    private fun requestPermissions() {
        val needed = buildList {
            add(Manifest.permission.CAMERA)
            add(Manifest.permission.RECORD_AUDIO)
            // Required on Android 13+ for the foreground service notification
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
                add(Manifest.permission.POST_NOTIFICATIONS)
            }
        }
        val missing = needed.filter {
            ContextCompat.checkSelfPermission(this, it) != PackageManager.PERMISSION_GRANTED
        }
        if (missing.isNotEmpty()) {
            ActivityCompat.requestPermissions(this, missing.toTypedArray(), 1)
        }
    }

    override fun onBackPressed() {
        if (webView.canGoBack()) webView.goBack() else super.onBackPressed()
    }
}
